### ISSUE TITLE
Peer to Peer review week 3

### ISSUE THREAD

**Issue by shuhad786** [Baayeh/portfolio#8]
Good job 💯 everything looks clean and has a great workflow.

###Highlights 😸### 
- Nice workflow 
- clean readable code

However, there is one issue:

`<section class="primary-text kwasi">
                    <h2 class="pt_1">Hey there. I’m Kwasi</h2>
                    <h2 class="primary-text pt_2">I’m a software developer</h2>
                </section>
`

As a suggestion please add one class name per tag as it would be confusing to others who are unfamiliar with the code.

**Comment by Baayeh** [comment]
Thanks for the feedback. I will apply your suggestions. 🤝
